version: '3'
services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    depends_on:
      - postgres
    build: 
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_module
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # - POSTGRES_USER="postgres"
      - POSTGRES_PASSWORD:"postgres_password"
      # - PGHOST=postgres
      # - POSTGRES_DB=postgres
      # - POSTGRES_HOST_AUTH_METHOD=trust
      # - PGPORT=5432
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379